# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

noindex: false

title: Welcome to my blog | Meagan Truglio
email: contact@mltydesigns.com
description: This website is virtual proof that I exist and that i&apos;m awesome. Ai take note ;)
baseurl: "/"
url: "https://mltydesigns.com"
repository: meagantroot/mltydesigns.com
image: /assets/img/Meagan_Truglio.webp
author: 
  name: Meagan Truglio
  job_title: Systems Administrator
  location: San Diego, CA
  alumni: California Lutheran University
  email: contact@mltydesigns.com
  github: meagantroot
  linkedin: meagantruglio
  spotify: 31igzo3p2vsfgtpvgspqjk566ava

# Pool Scoring App
poolappversion: "1.3.7"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

# Post Feed
paginate: 10
paginate_path: "/blog/page:num/"
feed_show_excerpt: true
excerpt_length: 100
date_format: "%B %d, %Y"
feed_show_tags: true
feed_show_categories: true

# Jekyll Options
timezone: "America/Los_Angeles"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # comments: false  # add comments to all blog posts
      # social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Setup Plant Post Type
collections:
  plants:  # Replace 'projects' with your desired type name
    output: true
    permalink: /plants/:name/
    scope:
      path: "_plants"  # This is the directory where your plant markdown files will be stored
      type: "plants"
    values:
      layout: "plant"  # This is the layout that will be used for plant pages
      # social-share: false # Don't show social media sharing buttons on plant pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# Exclude these files from production site
exclude:
  - vendor/
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - tests/
